---
output:
  bookdown::pdf_document2:
header-includes: \usepackage{graphicx}
    \usepackage{setspace}
    \doublespacing
    \usepackage{lineno}
    \linenumbers
---
```{r setup, include = F}

rm(list=ls())

#Load knitr 
library(knitr)

#Set some options
options(na.action='na.fail')
opts_knit$set(root.dir = '..')
opts_chunk$set(echo=FALSE,
               warning=FALSE,
               message=FALSE,
               fig.width=8,
               fig.height=8,
               fig.path = "../Figures/")

```

```{r load and clean, include = F}

#Load and clean data
source('Scripts/GWAS_sims_LOAD.R')
source('Scripts/GWAS_sims_FUNCTIONS.R')
source('Scripts/GWAS_sims_CLEAN.R')

```


#GWAS simulations - results


\pagebreak

###GWAS - QTL effect sizes

test ref to at figure \@ref(fig:Fig_QTL_effects)

```{r Fig_QTL_effects}
g4_2 <- g4[,colnames(g4) %in% colnames(g1)]
g4_2$Nids <- g4_2$Nids*10

temp <- rbind(g1,g4_2)
temp$Scenario <- rep(c(1,4),c(nrow(g1),nrow(g4_2)))


Fig1 <-  subset(temp,(SNP.Name %in% paste0("Q",c(1:10)))) %>%
         ddply(.(Nids,Nsnps,HistN,Full.Iteration.ID,Scenario),
              summarise,
              N_Sig_QTL = sum(Sig.Corrected == "yes")
              ) %>%
        ggplot(
             aes(x = factor(Scenario), y = N_Sig_QTL,col = factor(Scenario))
             )+
            geom_boxplot()+
            ylim(c(0,10))+
            geom_hline(aes(yintercept = 10),lty = 2)+
            facet_grid(factor(Nids)~factor(Nsnps))+
            theme_bw()

Fig1

```
**Figure ** Density blah blah

\pagebreak

###GWAS - Non-QTL hits

```{r Figure 2}
g4_2 <- g4[,colnames(g4) %in% colnames(g1)]
g4_2$Nids <- g4_2$Nids*10

temp <- rbind(g1,g4_2)
temp$Scenario <- rep(c(1,4),c(nrow(g1),nrow(g4_2)))

Fig2 <-  subset(temp,!(SNP.Name %in% paste0("Q",c(1:10)))) %>%
  ddply(.(Nids,Nsnps,HistN,Full.Iteration.ID,Scenario),
              summarise,
              N_Sig_QTL = sum(Sig.Corrected == "yes")
              ) %>%
        ggplot(
             aes(x = factor(Scenario), y = N_Sig_QTL,col = factor(Scenario))
             )+
            geom_boxplot()+
            facet_grid(factor(Nids)~factor(Nsnps))+
            theme_bw()

Fig2

```
**Figure 2** Density blah blah

\pagebreak



###Heritability

```{r Figure 3}
h4_2 <- h4[,colnames(h4) %in% colnames(h1)]
h4_2$Nids <- h4_2$Nids*10
# h4$Nsnps[h4$Nsnps > 200000] <- 200000



temp <- rbind(h1,h4_2)
temp$Scenario <- rep(c(1,4),c(nrow(h1),nrow(h4_2)))

Fig3 <- ggplot(temp,aes(x = factor(Scenario), y = H2,col = factor(Scenario)))+
          geom_boxplot()+
          facet_grid(factor(Nids)~factor(Nsnps))+
          geom_hline(aes(yintercept = (0.4)),lty = 2)+
          theme_bw()+
          xlab("Scenario")+
          ylab("Heritability")

Fig3

```
**Figure 3** Density blah blah


###Regional heritability

```{r Figure 4}

Fig4 <- subset(q1, Merged == F) %>%
        ggplot(
             aes(x = Var, y= qtl2)
             )+
            geom_smooth(method = "lm")+
            facet_grid(factor(Nids)~factor(Nsnps))+
            geom_abline(aes(intercept = 0,slope = 1),lty = 2)+
  geom_point()+
            theme_bw()

Fig4

```




```{r test}

temp <- subset(g4,Nsnps == 5000)

Fig2 <-  subset(temp,!(SNP.Name %in% paste0("Q",c(1:10)))) %>%
  ddply(.(Nids,Nsnps,HistN,Ne,Full.Iteration.ID),
              summarise,
              N_Sig_QTL = sum(Sig.Corrected == "yes")
              ) %>%
        ggplot(
             aes(x = factor(Nids), y = N_Sig_QTL,col = factor(Nids))
             )+
            geom_jitter()+
            facet_grid(factor(HistN)~factor(Ne))+
            theme_bw()

Fig2


```

